services:
    web:
        build:
            dockerfile: ./Dockerfile
        command: >
            sh -c "
            gunicorn megano.wsgi:application --bind 0.0.0.0:8000
            "
        volumes:
            - ./src:/app
        ports:
            - 8000:8000
        env_file:
             - .env
        depends_on:
            - db

    db:
        image: postgres:16
        container_name: my_postgres_db
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
